"""empty message

Revision ID: 7f8d5ceb470d
Revises: d08d2c2e68fe
Create Date: 2016-07-30 19:27:34.462169

"""

# revision identifiers, used by Alembic.
revision = '7f8d5ceb470d'
down_revision = 'd08d2c2e68fe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_logged_in', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_column('user', 'lname')
    op.drop_column('user', 'createdOn')
    op.drop_column('user', 'updatedOn')
    op.drop_column('user', 'fname')
    op.drop_column('user', 'lastLoggedIn')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastLoggedIn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('fname', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updatedOn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('createdOn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('lname', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'last_logged_in')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'created_on')
    ### end Alembic commands ###
