"""empty message

Revision ID: d08d2c2e68fe
Revises: None
Create Date: 2016-07-30 19:20:56.005059

"""

# revision identifiers, used by Alembic.
revision = 'd08d2c2e68fe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.Column('updatedOn', sa.DateTime(), nullable=True),
    sa.Column('lastLoggedIn', sa.DateTime(), nullable=True),
    sa.Column('active', sa.SmallInteger(), nullable=True),
    sa.Column('fname', sa.String(length=120), nullable=True),
    sa.Column('lname', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
